//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentModel1._5.CommonModel {
    
    
    public partial class Field {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// LblTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxLabel LblTitle;
        
        /// <summary>
        /// TxtFieldName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox TxtFieldName;
        
        /// <summary>
        /// TxtFieldAliax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox TxtFieldAliax;
        
        /// <summary>
        /// TxtTips control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox TxtTips;
        
        /// <summary>
        /// TxtDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxMemo TxtDescription;
        
        /// <summary>
        /// RadlEnableNull control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList RadlEnableNull;
        
        /// <summary>
        /// RadlEnableShowOnSearchForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList RadlEnableShowOnSearchForm;
        
        /// <summary>
        /// RadDisabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList RadDisabled;
        
        /// <summary>
        /// IsReadOnly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList IsReadOnly;
        
        /// <summary>
        /// RadTextType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadTextType;
        
        /// <summary>
        /// RadMultipleTextType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMultipleTextType;
        
        /// <summary>
        /// RadMultipleHtmlTextType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMultipleHtmlTextType;
        
        /// <summary>
        /// PnlRadioType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton PnlRadioType;
        
        /// <summary>
        /// RadNumberType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadNumberType;
        
        /// <summary>
        /// RadMoneyType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMoneyType;
        
        /// <summary>
        /// RadDateType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadDateType;
        
        /// <summary>
        /// RadTimeType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadTimeType;
        
        /// <summary>
        /// RadHyperLinkType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadHyperLinkType;
        
        /// <summary>
        /// RadMobilephoneType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMobilephoneType;
        
        /// <summary>
        /// RadTelephoneType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadTelephoneType;
        
        /// <summary>
        /// RadColorType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadColorType;
        
        /// <summary>
        /// RadUserTextType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadUserTextType;
        
        /// <summary>
        /// RadTableField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadTableField;
        
        /// <summary>
        /// RadPictureType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadPictureType;
        
        /// <summary>
        /// RadMultiPictureType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMultiPictureType;
        
        /// <summary>
        /// RadFileType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadFileType;
        
        /// <summary>
        /// RadMultiFileType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadMultiFileType;
        
        /// <summary>
        /// RadRegionType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadRegionType;
        
        /// <summary>
        /// RadWordsType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadWordsType;
        
        /// <summary>
        /// RadCaptchaType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadCaptchaType;
        
        /// <summary>
        /// RadSelectUserType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadSelectUserType;
        
        /// <summary>
        /// RadSelectRegionType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadSelectRegionType;
        
        /// <summary>
        /// RadSelectRoleType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadSelectRoleType;
        
        /// <summary>
        /// RadSelectCodeType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadSelectCodeType;
        
        /// <summary>
        /// RadVoteCtrlType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButton RadVoteCtrlType;
        
        /// <summary>
        /// PnlText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlText;
        
        /// <summary>
        /// PnlTextWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlTextWidth;
        
        /// <summary>
        /// PnlTextHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlTextHeight;
        
        /// <summary>
        /// TxtTextMaxLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtTextMaxLength;
        
        /// <summary>
        /// PnlTextErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlTextErrorText;
        
        /// <summary>
        /// PnlTextNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlTextNullText;
        
        /// <summary>
        /// TxtTextDefaultValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox TxtTextDefaultValue;
        
        /// <summary>
        /// PnlMultiText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlMultiText;
        
        /// <summary>
        /// TxtMultiTextWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtMultiTextWidth;
        
        /// <summary>
        /// TxtMultiTextHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtMultiTextHeight;
        
        /// <summary>
        /// PnlMultiTextErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlMultiTextErrorText;
        
        /// <summary>
        /// PnlMultiTextNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlMultiTextNullText;
        
        /// <summary>
        /// TxtMultiDefault control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxMemo TxtMultiDefault;
        
        /// <summary>
        /// PnlEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlEditor;
        
        /// <summary>
        /// TxtEditorWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtEditorWidth;
        
        /// <summary>
        /// TxtEditorHight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtEditorHight;
        
        /// <summary>
        /// PnlEditorErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlEditorErrorText;
        
        /// <summary>
        /// PnlEditorDefault control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxHtmlEditor PnlEditorDefault;
        
        /// <summary>
        /// PnlRadio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlRadio;
        
        /// <summary>
        /// RadlChoiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList RadlChoiceType;
        
        /// <summary>
        /// PnlRadioWidthTd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow PnlRadioWidthTd;
        
        /// <summary>
        /// PnlRadioWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlRadioWidth;
        
        /// <summary>
        /// PnlRadioHeightTd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow PnlRadioHeightTd;
        
        /// <summary>
        /// PnlRadioHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlRadioHeight;
        
        /// <summary>
        /// RadlChoiceCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox RadlChoiceCode;
        
        /// <summary>
        /// PnlRadioErrorTip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlRadioErrorTip;
        
        /// <summary>
        /// PnlNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlNumber;
        
        /// <summary>
        /// PnlNumberWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlNumberWidth;
        
        /// <summary>
        /// PnlNumberHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlNumberHeight;
        
        /// <summary>
        /// PnlNumberMaxLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlNumberMaxLength;
        
        /// <summary>
        /// TxtNumberMinValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtNumberMinValue;
        
        /// <summary>
        /// TxtNumberMaxValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtNumberMaxValue;
        
        /// <summary>
        /// TxtNumberDisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox TxtNumberDisplayFormat;
        
        /// <summary>
        /// PnlNumberErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlNumberErrorText;
        
        /// <summary>
        /// PnlNumberNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlNumberNullText;
        
        /// <summary>
        /// TxtNumberDefaultValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtNumberDefaultValue;
        
        /// <summary>
        /// PnlCurrency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlCurrency;
        
        /// <summary>
        /// PnlCurrencyWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlCurrencyWidth;
        
        /// <summary>
        /// PnlCurrencyHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlCurrencyHeight;
        
        /// <summary>
        /// PnlCurrencyMaxLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlCurrencyMaxLength;
        
        /// <summary>
        /// TxtCurrencyMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtCurrencyMin;
        
        /// <summary>
        /// TxtCurrencyMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtCurrencyMax;
        
        /// <summary>
        /// PnlCurrencyDisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox PnlCurrencyDisplayFormat;
        
        /// <summary>
        /// PnlCurrencyErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlCurrencyErrorText;
        
        /// <summary>
        /// PnlCurrencyNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlCurrencyNullText;
        
        /// <summary>
        /// TxtCurrencyDefaultValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtCurrencyDefaultValue;
        
        /// <summary>
        /// PnlDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlDate;
        
        /// <summary>
        /// PnlDateWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlDateWidth;
        
        /// <summary>
        /// PnlDateHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlDateHeight;
        
        /// <summary>
        /// PnlDateDisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox PnlDateDisplayFormat;
        
        /// <summary>
        /// PnlDateErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlDateErrorText;
        
        /// <summary>
        /// PnlDateNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlDateNullText;
        
        /// <summary>
        /// RadlDateDefaultType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxDateEdit RadlDateDefaultType;
        
        /// <summary>
        /// PnlTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlTime;
        
        /// <summary>
        /// PnlTimeWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlTimeWidth;
        
        /// <summary>
        /// PnlTimeHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlTimeHeight;
        
        /// <summary>
        /// PnlTimeDisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox PnlTimeDisplayFormat;
        
        /// <summary>
        /// PnlTimeErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlTimeErrorText;
        
        /// <summary>
        /// RadlTimeDefaultType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTimeEdit RadlTimeDefaultType;
        
        /// <summary>
        /// PnlURL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlURL;
        
        /// <summary>
        /// PnlURLWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlURLWidth;
        
        /// <summary>
        /// PnlURLHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlURLHeight;
        
        /// <summary>
        /// PnlPhoneMobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlPhoneMobile;
        
        /// <summary>
        /// PnlPhoneMobileWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlPhoneMobileWidth;
        
        /// <summary>
        /// PnlPhoneMobileHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlPhoneMobileHeight;
        
        /// <summary>
        /// PnlPhoneMobileErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlPhoneMobileErrorText;
        
        /// <summary>
        /// PnlPhoneMobileDefaultText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlPhoneMobileDefaultText;
        
        /// <summary>
        /// PnlPhoneFixed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlPhoneFixed;
        
        /// <summary>
        /// PnlPhoneFixedWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlPhoneFixedWidth;
        
        /// <summary>
        /// PnlPhoneFixedHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlPhoneFixedHeight;
        
        /// <summary>
        /// PnlPhoneFixedErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlPhoneFixedErrorText;
        
        /// <summary>
        /// PnlPhoneFixedDefault control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlPhoneFixedDefault;
        
        /// <summary>
        /// PnlColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlColor;
        
        /// <summary>
        /// PnlColorWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlColorWidth;
        
        /// <summary>
        /// PnlColorHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlColorHeight;
        
        /// <summary>
        /// PnlColorErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlColorErrorText;
        
        /// <summary>
        /// PnlColorNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlColorNullText;
        
        /// <summary>
        /// PnlColorDefaultValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxColorEdit PnlColorDefaultValue;
        
        /// <summary>
        /// PnlCustomized control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlCustomized;
        
        /// <summary>
        /// PnlCustomizedWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlCustomizedWidth;
        
        /// <summary>
        /// PnlCustomizedHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlCustomizedHeight;
        
        /// <summary>
        /// PnlCustomizedDisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox PnlCustomizedDisplayFormat;
        
        /// <summary>
        /// PnlCustomizedErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlCustomizedErrorText;
        
        /// <summary>
        /// PnlCustomizedNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlCustomizedNullText;
        
        /// <summary>
        /// PnlCustomizedDefaultValue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlCustomizedDefaultValue;
        
        /// <summary>
        /// PnlTableField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlTableField;
        
        /// <summary>
        /// TableFieldtable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox TableFieldtable;
        
        /// <summary>
        /// TableFieldfield control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox TableFieldfield;
        
        /// <summary>
        /// PnlPicture control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlPicture;
        
        /// <summary>
        /// PnlImageWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlImageWidth;
        
        /// <summary>
        /// PnlImageHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlImageHeight;
        
        /// <summary>
        /// TxtImageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtImageSize;
        
        /// <summary>
        /// PnlImageRadlHasWm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList PnlImageRadlHasWm;
        
        /// <summary>
        /// PnlImageRadWmStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList PnlImageRadWmStyle;
        
        /// <summary>
        /// PictureStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxDropDownEdit PictureStyle;
        
        /// <summary>
        /// PictureStyleList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxListBox PictureStyleList;
        
        /// <summary>
        /// PictureStyleButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxButton PictureStyleButton;
        
        /// <summary>
        /// PnlMultiPicture control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlMultiPicture;
        
        /// <summary>
        /// PnlMultipleImageWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlMultipleImageWidth;
        
        /// <summary>
        /// PnlMultipleImageHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlMultipleImageHeight;
        
        /// <summary>
        /// PnlMultipleImageMaxSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit PnlMultipleImageMaxSize;
        
        /// <summary>
        /// PnlMultipleImageHasWm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList PnlMultipleImageHasWm;
        
        /// <summary>
        /// PnlMultipleImageWmStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList PnlMultipleImageWmStyle;
        
        /// <summary>
        /// MultiPictureStyle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxDropDownEdit MultiPictureStyle;
        
        /// <summary>
        /// MultiPictureStyleList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxListBox MultiPictureStyleList;
        
        /// <summary>
        /// MultiPictureStyleButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxButton MultiPictureStyleButton;
        
        /// <summary>
        /// PnlFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlFile;
        
        /// <summary>
        /// TxtFileSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtFileSize;
        
        /// <summary>
        /// PnlMultiFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlMultiFile;
        
        /// <summary>
        /// TxtFilesSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxSpinEdit TxtFilesSize;
        
        /// <summary>
        /// PnlRegion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlRegion;
        
        /// <summary>
        /// PnlKeyword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlKeyword;
        
        /// <summary>
        /// PnlCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlCaptcha;
        
        /// <summary>
        /// PnlSelectUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlSelectUser;
        
        /// <summary>
        /// PnlSelectDepartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlSelectDepartment;
        
        /// <summary>
        /// PnlSelectRole control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlSelectRole;
        
        /// <summary>
        /// PnlSelectCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlSelectCode;
        
        /// <summary>
        /// PnlSelectCodeErrorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlSelectCodeErrorText;
        
        /// <summary>
        /// PnlSelectCodeNullText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxTextBox PnlSelectCodeNullText;
        
        /// <summary>
        /// PnlCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxComboBox PnlCode;
        
        /// <summary>
        /// SingleOrMultiple control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList SingleOrMultiple;
        
        /// <summary>
        /// DisplayFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxRadioButtonList DisplayFormat;
        
        /// <summary>
        /// PnlVote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PnlVote;
        
        /// <summary>
        /// EBtnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxButton EBtnSubmit;
        
        /// <summary>
        /// BtnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxSpellChecker.ASPxButton BtnCancel;
        
        /// <summary>
        /// HdnFieldLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnFieldLevel;
        
        /// <summary>
        /// HdnFieldType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnFieldType;
        
        /// <summary>
        /// HdnOrderId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnOrderId;
        
        /// <summary>
        /// HdnDisabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnDisabled;
        
        /// <summary>
        /// hfKeyFieldList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfKeyFieldList;
        
        /// <summary>
        /// ModelNameHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ModelNameHidden;
        
        /// <summary>
        /// EditModeHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField EditModeHidden;
    }
}
